server:
  port: 8081

spring:
  datasource:

    # mysql
    #url: jdbc:mysql://localhost:3306/student?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver

    # H2 data_source
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  # H2
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        id:
          new_generator_mapping: false

  security:
    user:
      name: user
      password: pass

  data:
    rest:
      base-path: /api
